version: "3"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PGID=abc
      - PUID=abc
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - MEDIA_DIR=/volume1/Storage/BabySearch
    volumes:
      - ./transmission/config:/config
      - ./transmission/watch:/watch
      - /volume1/Storage/BabySearch:/downloads
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  babysearch:
    build: .
    container_name: babysearch
    depends_on:
      - transmission
    environment:
      - PGID=abc
      - PUID=abc
      - BASE_URL=https://apibay.org/
      - HOME_BASE=http://0.0.0.0:9091/transmission/rpc
      - API_PORT=9000
      - MEDIA_DIR=/volume1/Storage/BabySearch
    restart: unless-stopped
    network_mode: service:transmission
