version: "3"
services:
  vpn:
    image: bubuntux/nordvpn:3.7.4
    container_name: vpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=maverick.marq@gmail.com
      - "PASS=<password>"
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/24
      - TZ=America/Los_Angeles
      - DNS=1.1.1.1,8.8.8.8
      - FIREWALL=1
    ports:
      - 8000:8000
      - 8080:8080
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      - 1080:1080
    restart: unless-stopped
      
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    depends_on: 
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
    volumes:
      - /volume1/docker/transmission/config:/config
      - /volume1/Storage/Downloads:/downloads
      - /volume1/docker/transmission/watch:/watch
    restart: unless-stopped
    network_mode: service:vpn
  
  babysearch:
    build: .
    container_name: babysearch-vpn
    depends_on:
      - vpn
      - transmission
    environment:
      - BASE_URL=https://thepiratebay.org/
      - HOME_BASE=http://0.0.0.0:9091/transmission/rpc
      - API_PORT=8000
    restart: unless-stopped
    network_mode: service:vpn